language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

before_install: pip install Cython
install: python setup.py install
script: coverage run --source=bencoder setup.py -q nosetests
after_success: coveralls
