version: '{branch}-{build}'
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  PYPI_PASSWD:
    secure: pp1j5lAB9NN8ZDasgY+oxoGrNw0+4gGzbNZmHVwJkCzUyrNBP5ZIuCrwjmx4q6ifg7RMiE3bVt9MljFCJh3XpsvVOAcx+AGKsHSjtXd40HM=
init:
  - ps: "ls C:/Python*"

install:
  - choco install python.pypy > pypy-inst.log 2>&1 || (type pypy-inst.log & exit /b 1)
  - SET PATH=C:\Python35;C:\Python35\scripts;C:\tools\pypy\pypy;%PATH%
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - pip install -r dev-requirements.txt

build: off

test_script:
  - tox

after_test:
  - pip install codecov
  - codecov
  - del bencoder.c
  - tox -c tox-wheels.ini
  - ps: "ls wheelhouse/*"

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          $env:Path += ";C:\Python35;C:\Python35\scripts"
          pip install twine
          twine upload --username whtsky --password $env:PYPI_PASSWD wheelhouse/bencoder*.whl
      }

artifacts:
  - path: wheelhouse/bencoder*.whl
