environment:
  password:
    secure: pp1j5lAB9NN8ZDasgY+oxoGrNw0+4gGzbNZmHVwJkCzUyrNBP5ZIuCrwjmx4q6ifg7RMiE3bVt9MljFCJh3XpsvVOAcx+AGKsHSjtXd40HM=

  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python26-x64"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_ARCH: "64"

init:
  - "ECHO Python %PYTHON%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - "pip install --disable-pip-version-check --user --upgrade pip wheel"
  - "pip install --user cython"

build_script:
  - "python setup.py install"

test_script:
  - "python setup.py test"

deploy_script:
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=whtsky                             >> %USERPROFILE%\\.pypirc
  - echo password=%password%                         >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - ps: if($env:APPVEYOR_REPO_TAG -eq $TRUE) { "python -W ignore setup.py bdist_wheel upload" }

deploy : on